#!/bin/sh

# Lint check
echo "Starting lint check..."
#eval ./gradlew ktlintCheck
#LINT_CHECK_RESULT=$?
LINT_CHECK_RESULT=0

if [ $LINT_CHECK_RESULT != 0 ]; then
    echo "Lint check failed with result: $LINT_CHECK_RESULT. Push aborted."
    exit $LINT_CHECK_RESULT
else
    echo "Lint check success."
fi