scicms-core:
  db-schema:
    path: src/main/resources/dbschema
    seed-on-init: true
  default-locale: en-US
  security:
    jwt-token:
      id: scisolutionsJWT
      secret: scisolutionsSecretKey
      expiration-interval-millis: 1_800_000

server:
  port: 8079

spring:
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    username: scicms
    password: scicms
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/scicms
#    username: scicms
#    password: scicms

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  file:
    name: logs/scicms-core.log
  logback:
    rollingpolicy:
      max-history: 7
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    ru.scisolutions.scicmscore: DEBUG
