scicms-core:
  data:
    data-sources:
      main:
#        driver-class-name: oracle.jdbc.OracleDriver
#        jdbc-url: jdbc:oracle:thin:@//localhost:1521/xepdb1
#        username: scicms
#        password: scicms
        jdbc-url: jdbc:${MAIN_DB_TYPE}://${MAIN_DB_HOST}:${MAIN_DB_PORT:5432}/${MAIN_DB_NAME}
        username: ${MAIN_DB_USERNAME}
        password: ${MAIN_DB_PASSWORD}
        maximum-pool-size: 5
        minimum-idle: 1
#      aux:
##        driver-class-name: org.postgresql.Driver
#        jdbc-url: jdbc:postgresql://localhost:5432/scicms
#        username: scicms
#        password: scicms
#        maximum-pool-size: 5
#        minimum-idle: 1
    default-limit: 20
    max-limit: 1000
    cache-expiration-minutes: 10
    item-template-cache-expiration-minutes: 1440
    item-cache-expiration-minutes: 1440
    trim-strings: true
  i18n:
    default-locale: en-US
    include-in-unique-index: true
  media:
    provider: local
    provider-options:
      base-path: D:/storage
      create-directories: true
  schema:
    path: build/resources/main/schema
    use-file-checksum: false # TODO: true in production to prevent restoring changed (made via API) items from scheme files
    seed-on-init: true
    delete-if-absent: false
    item-lock-lock-duration-seconds: 300
    try-recreate-attributes: true
  security:
    jwt-token:
      id: scisolutionsJWT
      secret: scisolutionsSecretKey
      expiration-interval-millis: 86_400_000
    registration-disabled: false
  versioning:
    include-in-unique-index: true

dgs:
  graphql:
    schema-locations: classpath*:graphql/**/*.graphql*

server:
  error:
    include-stacktrace: on_param
  port: 8079

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mail:
    host: ''
    port: 25
    username: ''
    password: ''

logging:
  file:
    name: logs/scicms-core.log
  logback:
    rollingpolicy:
      max-history: 7
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.springframework.jdbc.core.JdbcTemplate: debug
#    org.springframework.jdbc.core.StatementCreatorUtils: trace
    ru.scisolutions.scicmscore: debug
