version: "3.7"

services:
  postgres:
    build: ./postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  redis:
    build: ./redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
