coreVersion: v1
kind: Item
includeTemplates:
  - default
  - versioned
  - localized
metadata:
  name: product
  displayName: Product
  pluralName: products
  displayPluralName: Products
  dataSource: main
  tableName: products
  titleAttribute: name
  description: Products
  icon: ContainerOutlined
  core: false
  performDdl: true
  versioned: true
  manualVersioning: false
  localized: true
  notLockable: false
spec:
  attributes:
    name:
      type: string
      columnName: name
      displayName: Name
      description: Name
      required: true
      unique: true
      length: 50
      colWidth: 150
      fieldWidth: 300
    displayName:
      type: string
      columnName: display_name
      displayName: Display Name
      description: Display Name
      length: 50
      colWidth: 200
      fieldWidth: 300
    description:
      type: string
      columnName: description
      displayName: Description
      description: Description
      length: 250
      colWidth: 200
    parts:
      type: relation
      relType: oneToMany
      target: part
      mappedBy: product
      displayName: Parts
      description: Parts
