coreVersion: v1
kind: Item
includeTemplates:
  - defaultItemTemplate
metadata:
  name: product
  dataSource: aux
  tableName: products
  displayName: Product
  displayAttrName: name
  singularName: product
  pluralName: products
  description: Products
  core: false
  performDdl: true
  versioned: true
  manualVersioning: false
  notLockable: false
  localized: true
spec:
  attributes:
    name:
      type: string
      columnName: name
      displayName: Name
      description: Name
      required: true
      unique: true
      length: 50
    displayName:
      type: string
      columnName: display_name
      displayName: Display Name
      description: Display Name
      length: 50
    description:
      type: string
      columnName: description
      displayName: Description
      description: Description
      length: 250
    parts:
      type: relation
      relType: oneToMany
      target: part
      mappedBy: product
      displayName: Parts
      description: Parts
