coreVersion: v1
kind: Item
includeTemplates:
  - defaultItemTemplate
metadata:
  name: product
  dataSource: main
  tableName: products
  displayName: Product
  singularName: product
  pluralName: products
  description: Products
  core: false
  performDdl: true
  versioned: true
  manualVersioning: false
  notLockable: false
  localized: false
spec:
  properties:
    name:
      type: string
      columnName: name
      displayName: Name
      description: Name
      required: true
      length: 50
    displayName:
      type: string
      columnName: display_name
      displayName: Display Name
      description: Display Name
      length: 50
    description:
      type: string
      columnName: description
      displayName: Description
      description: Description
      length: 250
